model:
  checkpoint: null
  config: null

# Data Configuration
data:
  data_dir: "./data"
  batch_size: 64
  num_workers: 4
  pin_memory: true

# Output Configuration
output:
  output_dir: null
  save_plots: true
  save_predictions: false

# Device Configuration
device:
  device: "auto"