# Dataset Configuration
dataset:
  name: "food101"
  data_dir: "./data"
  val_split: 0.1
  num_workers: 4
  pin_memory: true

# Model Configuration
model:
  model_type: "StandardViT"
  img_size: 224
  num_classes: 101
  patch_size: 16
  embed_dim: 768
  depth: 12
  num_heads: 12 
  mlp_ratio: 4.0
  dropout: 0.1
  attention_dropout: 0.1
  projection_dropout: 0.1
  qkv_bias: true
  activation: "gelu"
  layer_norm_eps: 0.000001
  
  # Kernel for linear attention (LAViT only): elu or relu
  linear_attention_kernel: "elu"

# Training Configuration
training:
  epochs: 100 
  batch_size: 16
  learning_rate: 0.0001 
  weight_decay: 0.05
  optimizer: "adamw"
  scheduler: "cosine"
  warmup_epochs: 10
  min_lr: 0.00000001
  save_freq: 10
  print_freq: 25
  early_stopping: 15

# Experiment Configuration
experiment:
  experiment_dir: "experiments"
  run_name: "run001"
  resume: null
  seed: 42
  device: "auto"