# Dataset Configuration
dataset:
  name: "stl10"
  data_dir: "./data"
  val_split: 0.2
  num_workers: 4
  pin_memory: true

# Model Configuration
model:
  model_type: "StandardViT"
  img_size: 96     
  num_classes: 10
  patch_size: 8
  embed_dim: 384
  depth: 12
  num_heads: 6  
  mlp_ratio: 4.0
  dropout: 0.1
  attention_dropout: 0.1
  projection_dropout: 0.1
  qkv_bias: true
  activation: "gelu"
  layer_norm_eps: 0.000001
  
  # Kernel for linear attention (LAViT only): elu or relu
  linear_attention_kernel: "elu"

# Training Configuration
training:
  epochs: 200
  batch_size: 32
  learning_rate: 0.0003
  weight_decay: 0.01
  optimizer: "adamw"
  scheduler: "cosine"
  warmup_epochs: 15
  min_lr: 0.00000001
  save_freq: 20
  print_freq: 10
  early_stopping: 25

# Experiment Configuration
experiment:
  experiment_dir: "experiments"
  run_name: "run001"
  resume: null
  seed: 42
  device: "auto"